### ISSUE TITLE
Pipes beyond stdin/stdout/stderr?

### ISSUE THREAD

**Issue by nazar-pc** [oconnor663/os_pipe.rs#21]
I find it is rather difficult to work with custom fds beyond those standard ones.
Is it possible to use this crate to create `fd 3`, `fd 4` and so on?

An example would be really useful to have if it is the case.

I'm trying to create Rust wrapper for a library that essentially communicates with a worker process and it has some more file descriptors, which in Node.js look like this: https://github.com/versatica/mediasoup/blob/371d3df8e3871d3f4046ab47d5c2b76df56b72e0/src/Worker.ts#L284

**Comment by oconnor663** [comment]
Yes, `PipeReader` and `PipeWriter` both implement [`std::os::unix::io::FromRawFd`](https://doc.rust-lang.org/std/os/unix/io/trait.FromRawFd.html) and [`std::os::windows::io::FromRawHandle`](https://doc.rust-lang.org/std/os/windows/io/trait.FromRawHandle.html). You can use those APIs to construct pipe objects from your custom file descriptors. (You can also construct standard `File` objects that way.) Unfortunately this requires some `unsafe` code, because these objects need to have unique ownership of the file descriptor they contain. (If you make two `PipeReaders` out of the same fd, the first one to get dropped will close the shared fd, and if it gets reallocated then the second one will end up closing _someone else's_ fd.)

**Comment by nazar-pc** [comment]
Looks like it should work, but it doesn't, neither with this library nor when using nix directly (I'm on Linux).
Here is my question thread if you have time to look into it: https://users.rust-lang.org/t/piping-file-descriptors-beyond-std-io-out-err-to-child-process/48089

**Comment by oconnor663** [comment]
Unfortunately "it doesn't work" is pretty hard to interpret in this context. There are a lot of different ways a pipe might get closed or duped in some way you don't expect. Without looking at specific example code, it's hard to give any useful advice. I know you're running into this problem as part of a larger application, and that extracting a simple example is difficult. Would it be possible to write an example from scratch, where all the child process does is write `"hello world"` into the relevant pipe?

**Comment by nazar-pc** [comment]
Here are the instructions from the forum:
```
git clone https://github.com/nazar-pc/mediasoup.git
cd mediasoup
git checkout rust
npm i
cd rust
RUST_LOG=mediasoup=debug cargo test worker_manager::tests::worker_manager_test -- --nocapture
```

There is little of Rust code running when you do it, so should be relatively straightforward. The primary file to look at is `rust/src/worker/channels.rs`. It doesn't use this crate, but there was no difference when I refactored to it, so for now decided to keep less dependencies.

**Comment by oconnor663** [comment]
This is too much code for me to easily understand what's going on. If you could reduce the problem to a single `main.rs` file under 100 lines, I'd be happy to take another look.

**Comment by nazar-pc** [comment]
Turned out to be a bug in the library I was using that got fixed quickly: https://github.com/stjepang/async-fs/issues/4

Thank you!

**Comment by oconnor663** [comment]
> whenever async_fs::File wanted to "remember" the file cursor position before reading data from it, it would blow up with an error that says "Illegal seek". Then, that would case the thread to exit with that same error, thus dropping the async_fs::File, which is why "broken pipe" ends up being reported.

Oof! It sounds like your suffering has been for the benefit of all of us 😅
